In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('/content/pakwheels_scrapped.csv')

In [3]:
df['color'].value_counts()

color
White                                      4540
Black                                      2425
Silver                                     1410
Taffeta White                              1037
Super White                                 899
Grey                                        753
Attitude Black                              617
Blue                                        377
Silver Metallic                             350
Crystal Black                               328
Lunar Silver Metallic                       305
Polar White                                 268
Crystal Black Pearl                         234
Maroon                                      209
Gold                                        203
Pearl White                                 185
White Pearl Crystal Shine                   181
Burgundy                                    174
Red                                         164
Modern Steel Metallic                       162
Green                                       159
Alabaster Silver                            156
Solid White                                 138
Super white                                 127
Attitude Black Mica                         119
Black Metallic                              119
Medium Silver                               103
Beige                                       100
Black Mica                                   96
Diamond Black                                95
White                                        91
Black Mica Metallic                          89
Brown                                        88
Clear White                                  86
Onyx Black                                   78
Navy                                         76
Grey Graphite                                75
Urban Titanium                               73
Bronze                                       70
Gun Metallic                                 66
Snow White                                   64
 White                                       64
Graphite Grey                                64
Turquoise                                    63
Silver metallic                              62
White Pearl                                  59
Grenada Black Pearl                          59
York white                                   58
Silky Silver                                 57
 White Pearl Crystal Shine                   55
Diamond Metallic Black                       53
Teffeta White                                52
Unlisted                                     50
Metallic Grey                                50
Bright Silver Metallic                       49
Cherry Black                                 48
Polished Metal Metallic                      48
Steller White                                46
Charcoal Grey Pearl                          45
Black Pearl                                  43
Canyon Stone Silver Metallic                 42
Precious Wite Pearl                          41
Sparkling Silver                             41
Golden                                       40
Pearl Black                                  40
Snowy White                                  39
Frost White                                  34
Indigo                                       33
Purple                                       32
Arctic White                                 31
Ivory White                                  31
Turquoise Blue Metallic                      30
Sliver                                       29
white                                        28
White Orchid Pearl                           28
Strong Blue                                  27
Galaxy Black                                 27
Mythos Black Metallic                        26
Pearl Black                                  26
 Silver Metallic                             26
Shining White Pearl                          25
Blue Metallic                                24
Black Diamond                                24
Platinum White Pearl                         24
Black Diamond Metallic                       23
Vogue Silver Metallic                        23
Alpine White                                 23
Silky Silver Metallic                        23
Bluish Silver Metallic                       22
Superia White                                22
Bronze Mica                                  22
Olive Green                                  22
Stellar White                                21
Dark Blue                                    21
Celestial Black                              21
 White Pearl Mica                            21
Carbon Crystal Black                         20
Silver Mica Metallic                         19
Khaki White                                  19
Grey Metallic                                19
Phantom Black                                19
Black                                        18
White Pearl Crystal                          18
Cosmos Black                                 18
Obsidian Black                               17
Wine Red                                     17
Flaxen Mica                                  17
Fery Red                                     17
Beige Mica Metallic                          16
White White Pearl Crystal Shine              16
Warm Silver                                  16
Magenta                                      15
Cyprus Blue Pearl                            15
Silver                                       15
Light Blue                                   15
Shining White Pearl                          15
Pink                                         15
Ralley Red                                   15
Cool Silver Metallic                         14
Black Sand Pearl                             14
Orange                                       14
Diamond White                                14
Obsidian Black Metallic                      14
Quartz Black                                 14
Pearl White                                  14
Urban titanium                               14
Metallic Silver                              13
Manhattan Gray Metallic                      13
Phantom Brown                                13
Strong Blue Metallic                         13
Lunar Silver                                 13
Pure White                                   13
Cirullian Blue                               12
Attitude Black                               12
Dark Blue Mica Metallic                      12
Grey                                         12
Diamond White Metallic                       12
Moon Light Silver                            12
Lazer Blue Crystal Shine                     12
Fusion Black                                 11
Dorado Gold                                  11
Brillant White                               11
Black Sapphire Metallic                      11
Oxford Blue                                  11
Brilliant Black                              10
Yellow                                       10
Diamond Silver Metallic                      10
Granada Black Pearl                          10
Ski White                                    10
 Bright Silver Metallic                      10
Blue                                         10
 Platinum White Pearl                         9
Laser Blue Crystal Shine                      9
Glacier White                                 9
Cosmic Silver                                 9
Albastar Silver                               9
Premium Crystal Red Metallic                  9
Rallye Red                                    9
 Super White II                               8
Platinum Pearl White                          8
silver metallic                               8
Graphite                                      8
 Bluish Black Pearl                           8
Snow White Pearl                              8
Jet Grey                                      8
Luna Silver Metallic                          8
Brilliant Silver                              8
Space Gray                                    8
Panthera Metal                                8
 Crystal Black Pearl                          8
Piano Black                                   8
Super white                                   8
Dark Maroon                                   8
Black Sapphire                                7
Ebony                                         7
Ruse Black Metallic                           7
silver                                        7
Alabaster Silver Metallic                     7
Iridium Silver                                7
Pearl White Multi Coat                        7
Superior White                                7
York White                                    7
Ocean Blue                                    7
Night Black                                   7
Arctic Pearl                                  7
Gunmetal Gray                                 7
Hampton Gray                                  7
Dark Grey Mica Metallic                       7
Meteoroid Gray                                6
Sporty Blue Metallic                          6
Phantom black                                 6
Ash Gray                                      6
Dolomite White Metallic                       6
Harbour Grey                                  6
Silver Pearl                                  6
Designo Diamond White                         6
Mercury Blue                                  6
 Frost White                                  6
Sky Blue                                      6
Red Mica Metallic                             6
 Black                                        5
Green                                         5
Sliver                                        5
Deep lapis Blue Metallic                      5
Crystal White Pearl                           5
Satin Silver Metallic                         5
Pewter Grey Metallic                          5
Navy Blue                                     5
Matte Light Grey                              5
Habanero Red                                  5
Blade Silver                                  5
Full Moon Silver                              5
Bluish Black Pearl                            5
Pearl White III                               5
Fire Quartz Red Metallic                      5
Compagno Red                                  5
Dark Blue Mica                                4
 Warm Silver Metallic                         4
Mineral White                                 4
Midnight Blue                                 4
Sun Black                                     4
 Warm Grey Pearl Metallic                     4
Designo Cashmere White                        4
Metallic Blue Silver                          4
Teal Blue                                     4
Pearl White Metallic                          4
Dark Blue Mica Metallic Toning G              4
Two Tone                                      4
Bright Silver                                 4
Dark Green Mica                               4
Carnelian Red                                 4
Red Wine                                      4
Roman Silver                                  4
Glacier White Metallic                        4
 Pearl White III                              4
Celestite Gray                                4
Redwine                                       4
Red Vine                                      4
Metallic Mariner Blue                         4
Dover White                                   4
Dark Green                                    4
Neptune Blue                                  3
Armour Silver                                 3
Onxy Black                                    3
Misty Green Pearl                             3
Jungle Green                                  3
Grantic Verde Metallic                        3
Labrador Black Pearl                          3
 White Orchid Pearl                           3
Shalimar Rose Mist                            3
Pearl White Multi coat                        3
Dee Sea Green                                 3
Gold                                          3
Mellinnum Silver                              3
Pearl Ice White                               3
Metallic                                      3
Golden Black                                  3
Sapphire Black                                3
 Alabaster Silver Metallic                    3
Crystal Pearl                                 3
 Silky Silver Metallic                        3
Brilliant Blue                                3
Blizzard Pearl                                3
Carbon Black Metallic                         3
Daytona Grey                                  3
Metallic Black                                3
Splash Blue                                   3
 Grey Metallic                                3
Moonlight Silver                              3
Smart Black                                   3
Graphite Pearl                                3
 White Toning G                               3
Breeze Blue                                   3
Graphite Grey Pearl                           3
Hamilton White                                3
Aurora Black Pearl                            3
Dark Green Mica Metallic                      3
Premium Sunlight White Pearl                  3
Gray Metallic                                 3
Pearl Red                                     3
Nighthawk Black Pearl                         3
Dignity Brown Pearl Metallic                  3
Stealth Grey                                  3
Sensual Red Mica                              2
White Solid                                   2
Jet Black                                     2
Captiva Blue Pearl                            2
 Light Beige Metallic                         2
Off White                                     2
 Dark Blue Mica                               2
Super Black Pearl                             2
Storm Grey                                    2
Graphite grey                                 2
 Dark Green Mica Metallic                     2
Blue Crystal Metallic                         2
Designo Mocha Black Metal                     2
Black Mira                                    2
Metal Matallic                                2
Dark Metal Grey                               2
Cool Silver                                   2
Lime White Pearl Crystal Shine                2
Space Grey                                    2
Magneta                                       2
 Dark Blue Mica Metallic                      2
Cobalt Blue Pearl                             2
Rose Metallic                                 2
Ibis White                                    2
Pearl white                                   2
Pure Black                                    2
 Dark Green Mica                              2
Supersonic Red                                2
Iridium Silver Metallic                       2
Premium White Pearl                           2
Metal Stream Metallic                         2
Manufaktur Opalite White Bright               2
Cappuccino Brown Pearl                        2
Fuji White                                    2
Crystal black met                             2
Gravity Grey                                  2
Cayenne Red                                   2
Digital White Metallic                        2
Sonic White                                   2
Obsidian                                      2
Brilliant Silver Metallic                     2
Scarlett Red                                  2
Mist Rose                                     2
Aztec Green Pearl                             2
Dark Brown                                    2
Night Shade                                   2
Super Platinum Grey Metallic                  2
Light Pink                                    2
Brilliant Blue Metallic                       2
Gun Metalic                                   2
Red                                           2
Habareno Red                                  2
Artic Blue Pearl                              2
Dark Green                                    2
Comet White                                   2
Graphite Black                                2
Graphite Gray                                 2
Interstellar Grey                             2
Kemora Grey                                   2
Panthera Matel                                2
Sea Blue                                      2
Morning Mist Blue                             2
Lemon                                         2
Magnetic Force                                2
Lunar Grey                                    2
Metallic Red                                  2
Sea Green                                     2
Black Pearl Metallic                          2
Shinning Red                                  2
Selenite Grey                                 2
Antigua Blue Metallic                         2
 Beige Metallic                               2
Gravity Blue                                  2
Mineral White Metallic                        2
Steel Grey                                    2
Dolomite Brown Metallic                       2
Star Silver Metallic                          2
Premium White                                 2
Aqua Silver                                   2
Ice Grey Metallic                             2
Snow Pearl White                              2
Red Metallic                                  2
 Classy Red                                   1
Taffeta White II                              1
Starry Night Black                            1
Bronze Mica Metalic                           1
Util Red                                      1
Steel Gray                                    1
Twilight Grey Pearl                           1
Golden Gray                                   1
Sparkling Voilet                              1
Moonlight Blue Metallic                       1
Opal Silver Blue Metallic                     1
White Pearl                                   1
 dark bluish grey                             1
Moon Silver                                   1
Platinum White Pear                           1
Warm Silver Metallic                          1
Premium Sparkle Black Pearl                   1
Vogue Silver                                  1
Nocturn Blue Pearl                            1
1                                             1
Dark Moss Green                               1
Desert Beige                                  1
Skin                                          1
Scarlet Ember                                 1
Beige And Black (In Its Original Color)       1
Panthra Grey                                  1
Cherry Pearl Crystal                          1
Titanium Silver Metallic                      1
Champagne Beige Metallic                      1
Grey Metallic                                 1
 Brown Mica                                   1
Tanzanite Blue Metallic                       1
 Ivory Silver                                 1
Brown Mica                                    1
Volcano Sand                                  1
Grantive                                      1
 Premium Deep Rosso Pearl                     1
Crystal Black Met                             1
Dark Red Mica                                 1
Rhodium White Metallic                        1
Aquatic Blue                                  1
 Light Rose Mica Metallic                     1
Modern Steel                                  1
Graneite Var De Metalic                       1
Sky Blue                                      1
Magno Alanite Gray                            1
Hydro Blue                                    1
Special Edition                               1
Sonic Silver Metallic                         1
Frost Green Mica                              1
Metallic Saxony Blue                          1

In [4]:
df.head()

,link,name,year,price,Km_travelled,fuel_type,transmission,city,color,assembly,engine,body_type,interior,exterior,safety,comfort
0,https://www.pakwheels.com//used-cars/kia-sport...,KIA Sportage AWD 2020,2020,PKR 63.8 lacs,"50,000 km",Petrol,Automatic,Karachi,White,Imported,2000 cc,Crossover,"['Infotainment System', 'Android Auto', 'Apple...","['Alloy Wheels', 'Front Fog Lights', 'LED Head...","['ABS', 'Air Bags', 'Parking Sensors', 'Rear C...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."
1,https://www.pakwheels.com//used-cars/mercedes-...,Mercedes Benz E Class E200 2013,2013,PKR 97.5 lacs,"90,000 km",Petrol,Automatic,Islamabad,White,Imported,1800 cc,Sedan,"['Infotainment System', 'Front Speakers', 'Rea...","['Alloy Wheels', 'Front Fog Lights', 'LED Head...","['ABS', 'Air Bags', 'Tyre Pressure Monitoring ...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."
2,https://www.pakwheels.com//used-cars/mercedes-...,Mercedes Benz E Class E200 2011,2011,PKR 92 lacs,"94,000 km",Petrol,Automatic,Adda jahan khan,Obsidian Black Metallic,Imported,2100 cc,Sedan,"['Infotainment System', 'Front Speakers', 'Rea...","['Alloy Wheels', 'Front Fog Lights', 'Sun Roof']","['ABS', 'Air Bags', 'Tyre Pressure Monitoring ...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."
3,https://www.pakwheels.com//used-cars/toyota-aq...,Toyota Aqua S 2018,2018,PKR 52 lacs,"135,000 km",Hybrid,Automatic,Karachi,Grey,Imported,1500 cc,Hatchback,NaN,['Alloy Wheels'],"['ABS', 'Air Bags', 'Immobilizer Key', 'Power ...","['Power Mirrors', 'Keyless Entry', 'Power Stee..."
4,https://www.pakwheels.com//used-cars/hyundai-e...,Hyundai Elantra GLS 2021,2021,PKR 56.5 lacs,"62,000 km",Petrol,Automatic,Adda jahan khan,Silver,Local,2000 cc,Sedan,"['Infotainment System', 'Front Speakers', 'Rea...","['Alloy Wheels', 'DRLs', 'Sun Roof']","['ABS', 'Air Bags', 'Traction Control', 'Rear ...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."

In [5]:
df.isnull().sum()

link               0
name               0
year               0
price              0
Km_travelled       0
fuel_type          0
transmission       0
city               0
color              0
assembly           0
engine             0
body_type        304
interior        1220
exterior        4001
safety           819
comfort          545
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20823 entries, 0 to 20822
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   link          20823 non-null  object
 1   name          20823 non-null  object
 2   year          20823 non-null  int64
 3   price         20823 non-null  object
 4   Km_travelled  20823 non-null  object
 5   fuel_type     20823 non-null  object
 6   transmission  20823 non-null  object
 7   city          20823 non-null  object
 8   color         20823 non-null  object
 9   assembly      20823 non-null  object
 10  engine        20823 non-null  object
 11  body_type     20519 non-null  object
 12  interior      19603 non-null  object
 13  exterior      16822 non-null  object
 14  safety        20004 non-null  object
 15  comfort       20278 non-null  object
dtypes: int64(1), object(15)
memory usage: 2.5+ MB

In [8]:
df.shape

(20823, 16)

In [9]:
df.head(2)

,link,name,year,price,Km_travelled,fuel_type,transmission,city,color,assembly,engine,body_type,interior,exterior,safety,comfort
0,https://www.pakwheels.com//used-cars/kia-sport...,KIA Sportage AWD 2020,2020,PKR 63.8 lacs,"50,000 km",Petrol,Automatic,Karachi,White,Imported,2000 cc,Crossover,"['Infotainment System', 'Android Auto', 'Apple...","['Alloy Wheels', 'Front Fog Lights', 'LED Head...","['ABS', 'Air Bags', 'Parking Sensors', 'Rear C...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."
1,https://www.pakwheels.com//used-cars/mercedes-...,Mercedes Benz E Class E200 2013,2013,PKR 97.5 lacs,"90,000 km",Petrol,Automatic,Islamabad,White,Imported,1800 cc,Sedan,"['Infotainment System', 'Front Speakers', 'Rea...","['Alloy Wheels', 'Front Fog Lights', 'LED Head...","['ABS', 'Air Bags', 'Tyre Pressure Monitoring ...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."

# Check the price values

In [10]:
df = df[~(df['price']=='Call for price')]

In [11]:
df.shape

(20399, 16)

In [12]:
def convert_price_to_crore(price):
  if price[2] == 'lacs':
    return round(float(price[1])/100,2)
  elif price[2] == 'crore':
    return round(float(price[1]),2)

In [13]:
df_cleaned = df

In [14]:
df_cleaned['price'] = df['price'].str.split(' ').apply(convert_price_to_crore)

In [15]:
df_cleaned.head(3)

,link,name,year,price,Km_travelled,fuel_type,transmission,city,color,assembly,engine,body_type,interior,exterior,safety,comfort
0,https://www.pakwheels.com//used-cars/kia-sport...,KIA Sportage AWD 2020,2020,0.64,"50,000 km",Petrol,Automatic,Karachi,White,Imported,2000 cc,Crossover,"['Infotainment System', 'Android Auto', 'Apple...","['Alloy Wheels', 'Front Fog Lights', 'LED Head...","['ABS', 'Air Bags', 'Parking Sensors', 'Rear C...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."
1,https://www.pakwheels.com//used-cars/mercedes-...,Mercedes Benz E Class E200 2013,2013,0.97,"90,000 km",Petrol,Automatic,Islamabad,White,Imported,1800 cc,Sedan,"['Infotainment System', 'Front Speakers', 'Rea...","['Alloy Wheels', 'Front Fog Lights', 'LED Head...","['ABS', 'Air Bags', 'Tyre Pressure Monitoring ...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."
2,https://www.pakwheels.com//used-cars/mercedes-...,Mercedes Benz E Class E200 2011,2011,0.92,"94,000 km",Petrol,Automatic,Adda jahan khan,Obsidian Black Metallic,Imported,2100 cc,Sedan,"['Infotainment System', 'Front Speakers', 'Rea...","['Alloy Wheels', 'Front Fog Lights', 'Sun Roof']","['ABS', 'Air Bags', 'Tyre Pressure Monitoring ...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."

# km travelled

In [16]:
df['Km_travelled'].value_counts().head()

Km_travelled
100,000 km    573
150,000 km    462
200,000 km    443
120,000 km    241
80,000 km     220
Name: count, dtype: int64

In [17]:
df_cleaned['Km_travelled'] = df['Km_travelled'].str.split(' ').str.get(0).str.replace(',','').astype('int')

In [18]:
df['fuel_type'].value_counts()

fuel_type
Petrol      17128
Hybrid       2140
Diesel        711
Electric      248
PHEV          100
CNG            56
LPG            12
REEV            4
Name: count, dtype: int64

In [19]:
df.shape

(20399, 16)

# removing electric cars

In [20]:
df_cleaned =  df_cleaned[~((df_cleaned['engine'].str.contains('kWh')))]

# fixing engine columns

In [21]:
df_cleaned['engine'] = df_cleaned['engine'].str.split(' ').str.get(0).astype('int')

/tmp/ipython-input-3713714097.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['engine'] = df_cleaned['engine'].str.split(' ').str.get(0).astype('int')

In [22]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20151 entries, 0 to 20822
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   link          20151 non-null  object
 1   name          20151 non-null  object
 2   year          20151 non-null  int64
 3   price         20151 non-null  float64
 4   Km_travelled  20151 non-null  int64
 5   fuel_type     20151 non-null  object
 6   transmission  20151 non-null  object
 7   city          20151 non-null  object
 8   color         20151 non-null  object
 9   assembly      20151 non-null  object
 10  engine        20151 non-null  int64
 11  body_type     19850 non-null  object
 12  interior      18977 non-null  object
 13  exterior      16170 non-null  object
 14  safety        19336 non-null  object
 15  comfort       19610 non-null  object
dtypes: float64(1), int64(3), object(12)
memory usage: 2.6+ MB

In [23]:
df_cleaned.head(2)

,link,name,year,price,Km_travelled,fuel_type,transmission,city,color,assembly,engine,body_type,interior,exterior,safety,comfort
0,https://www.pakwheels.com//used-cars/kia-sport...,KIA Sportage AWD 2020,2020,0.64,50000,Petrol,Automatic,Karachi,White,Imported,2000,Crossover,"['Infotainment System', 'Android Auto', 'Apple...","['Alloy Wheels', 'Front Fog Lights', 'LED Head...","['ABS', 'Air Bags', 'Parking Sensors', 'Rear C...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."
1,https://www.pakwheels.com//used-cars/mercedes-...,Mercedes Benz E Class E200 2013,2013,0.97,90000,Petrol,Automatic,Islamabad,White,Imported,1800,Sedan,"['Infotainment System', 'Front Speakers', 'Rea...","['Alloy Wheels', 'Front Fog Lights', 'LED Head...","['ABS', 'Air Bags', 'Tyre Pressure Monitoring ...","['Power Seats', 'Power Mirrors', 'Rear AC Vent..."

# Interior

In [24]:
interiors = {'Infotainment System':7, 'Head Up Display (HUD)':9, 'Android Auto':5, 'Apple CarPlay':5, 'Front Speakers':3, 'Rear Speakers':4, 'Steering Switches':4, 'Paddle Shifters':6}

In [25]:
temp_df = df

In [26]:
def interior_score(x):
  if pd.isna(x):
    return 0
  score = 0
  for i in interiors.keys():
    if  i in x:
      score = score + interiors[i]
  return score

In [27]:
df_cleaned['interior_scores'] = df_cleaned['interior'].apply(interior_score)

/tmp/ipython-input-397030649.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['interior_scores'] = df_cleaned['interior'].apply(interior_score)

# Exterior

In [28]:
exterior =     {'Alloy Wheels': 6,
    'Front Fog Lights': 3,
    'LED Headlights': 7,
    'DRLs': 4,
    'Sun Roof': 8,
    'Panoramic Sunroof': 10}

In [29]:
def exterior_score(x):
  if pd.isna(x):
    return 0
  score = 0
  for i in exterior.keys():
    if  i in x:
      if i in ['Panoramic Sunroof','Sun Roof']:
        score = score + 0
      else:
        score = score + exterior[i]

  if 'Panoramic Sunroof' in x:
    return score + 10
  elif 'Sun Roof' in x:
    return score + 8
  else:
    return score

In [30]:

df_cleaned['exterior_scores'] = df_cleaned['exterior'].apply(exterior_score)

/tmp/ipython-input-1249068295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['exterior_scores'] = df_cleaned['exterior'].apply(exterior_score)

# Safety

In [31]:
safety = {
    'Air Bags': 10,
    'ABS': 8,
    'Traction Control': 7,
    'Tyre Pressure Monitoring System (TPMS)': 5,
    '360 Camera': 8,
    'Rear Camera': 6,
    'Front Camera': 4,
    'Parking Sensors': 5,
    'Immobilizer Key': 6,
    'Power Locks': 3
}

In [32]:
def safety_score(x):
  if pd.isna(x):
    return 0
  score = 0
  for i in safety.keys():
    if  i in x:
      score = score + safety[i]
  return score

In [33]:
df_cleaned['safety_scores'] = df_cleaned['safety'].apply(safety_score)

/tmp/ipython-input-3335143895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['safety_scores'] = df_cleaned['safety'].apply(safety_score)

# Comfort

In [34]:
comfort = {
    'Ventilated Seats': 10,
    'Heated Seats': 8,
    'Power Seats': 7,
    'Climate Control': 7,
    'Cruise Control': 6,
    'Push Start': 6,
    'Keyless Entry': 5,
    'Rear AC Vents': 5,
    'Power Mirrors': 4,
    'Power Steering': 2,
    'Air Conditioning': 2
}

In [35]:
def comfort_score(x):
  if pd.isna(x):
    return 0
  score = 0
  for i in comfort.keys():
    if  i in x and i not in ['Air Conditioning','Climate Control']:
      score = score + comfort[i]

  if 'Climate Control' in x:
    return score + 7
  elif 'Air Conditioning' in x:
    return score + 2
  else:
    return score

In [36]:
df_cleaned['comfort_scores']  = df_cleaned['comfort'].apply(comfort_score)

/tmp/ipython-input-1577727626.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['comfort_scores']  = df_cleaned['comfort'].apply(comfort_score)

In [37]:
list(df_cleaned.iloc[0])

['https://www.pakwheels.com//used-cars/kia-sportage-2020-for-sale-in-quetta-11181625',
 'KIA Sportage AWD 2020',
 np.int64(2020),
 np.float64(0.64),
 np.int64(50000),
 'Petrol',
 'Automatic',
 'Karachi',
 'White',
 'Imported',
 np.int64(2000),
 'Crossover',
 "['Infotainment System', 'Android Auto', 'Apple CarPlay', 'Front Speakers', 'Rear Speakers', 'Steering Switches', 'Paddle Shifters']",
 "['Alloy Wheels', 'Front Fog Lights', 'LED Headlights', 'DRLs', 'Sun Roof', 'Panoramic Sunroof']",
 "['ABS', 'Air Bags', 'Parking Sensors', 'Rear Camera', 'Immobilizer Key', 'Power Locks']",
 "['Power Seats', 'Power Mirrors', 'Rear AC Vents', 'Climate Control', 'Cruise Control', 'Push Start', 'Keyless Entry', 'Power Steering', 'Air Conditioning']",
 np.int64(34),
 np.int64(30),
 np.int64(38),
 np.int64(42)]

In [38]:
df_cleaned.head(1)

,link,name,year,price,Km_travelled,fuel_type,transmission,city,color,assembly,engine,body_type,interior,exterior,safety,comfort,interior_scores,exterior_scores,safety_scores,comfort_scores
0,https://www.pakwheels.com//used-cars/kia-sport...,KIA Sportage AWD 2020,2020,0.64,50000,Petrol,Automatic,Karachi,White,Imported,2000,Crossover,"['Infotainment System', 'Android Auto', 'Apple...","['Alloy Wheels', 'Front Fog Lights', 'LED Head...","['ABS', 'Air Bags', 'Parking Sensors', 'Rear C...","['Power Seats', 'Power Mirrors', 'Rear AC Vent...",34,30,38,42

In [39]:
df_cleaned.to_csv('pakwheels_cleaned.csv',index=False)