In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [20]:
df  = pd.read_csv('/content/pakwheels_clean.csv')

In [21]:
# df = pd.read_csv('/content/pakwheels_cleaned.csv')

In [22]:
df.isnull().sum()

year                 0
price                0
Km_travelled         0
fuel_type            0
transmission         0
city                 0
color              635
assembly             0
engine               0
body_type          162
interior_scores      0
exterior_scores      0
safety_scores        0
comfort_scores       0
company              0
dtype: int64

In [23]:
df[df['color'].isnull()]

,year,price,Km_travelled,fuel_type,transmission,city,color,assembly,engine,body_type,interior_scores,exterior_scores,safety_scores,comfort_scores,company
40,2018,0.53,128000,Petrol,Automatic,Lahore,NaN,Local,1800.0,Sedan,23.0,4.0,40.0,35.0,Honda
50,2020,0.58,83600,Petrol,Automatic,Sindh,NaN,Local,1800.0,Sedan,29.0,28.0,44.0,30.0,Toyota
57,2022,0.69,65000,Petrol,Automatic,Islamabad,NaN,Local,1800.0,Sedan,24.0,21.0,44.0,30.0,Toyota
75,2022,0.62,24000,Petrol,Automatic,Karachi,NaN,Imported,1500.0,Crossover,34.0,30.0,62.0,50.0,MG
80,2022,0.40,8000,Petrol,Automatic,Punjab,NaN,Local,1500.0,Sedan,18.0,21.0,43.0,24.0,Changan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11885,2012,0.28,145000,Petrol,Manual,Sindh,NaN,Local,1300.0,Sedan,10.0,0.0,23.0,8.0,Toyota
11886,2017,0.47,105000,Petrol,Automatic,Karachi,NaN,Local,1800.0,Sedan,18.0,21.0,40.0,35.0,Honda
11889,2022,6.05,25000,Petrol,Automatic,Un-Registered,NaN,Imported,3500.0,SUV,37.0,21.0,57.0,50.0,Toyota
11901,2025,0.79,12000,Petrol,Automatic,Karachi,NaN,Local,1800.0,Sedan,24.0,21.0,44.0,30.0,Toyota
11906,2013,0.30,100000,Petrol,Manual,Lahore,NaN,Local,1300.0,Sedan,10.0,0.0,23.0,8.0,Toyota

In [24]:
df[df['body_type'].isnull()]

,year,price,Km_travelled,fuel_type,transmission,city,color,assembly,engine,body_type,interior_scores,exterior_scores,safety_scores,comfort_scores,company
69,2007,0.22,139836,Petrol,Automatic,Islamabad,White,Imported,1500.0,NaN,7.0,0.0,33.0,13.0,Mitsubishi
72,2019,0.29,50000,Petrol,Automatic,Punjab,Blue,Imported,660.0,NaN,3.0,7.0,45.0,8.0,Toyota
123,1991,0.04,150000,Petrol,Manual,Karachi,Red,Local,1000.0,NaN,0.0,0.0,0.0,0.0,Nissan
125,2013,0.21,138000,Petrol,Automatic,Punjab,Black,Imported,660.0,NaN,7.0,0.0,27.0,8.0,Daihatsu
159,2022,0.38,24000,Hybrid,Automatic,Punjab,White,Imported,660.0,NaN,0.0,0.0,0.0,0.0,Nissan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,2019,0.54,140000,Petrol,Automatic,Un-Registered,Black,Imported,1500.0,NaN,0.0,0.0,0.0,0.0,Toyota
11620,1992,0.29,243000,Diesel,Automatic,Lahore,Silver,Imported,2500.0,NaN,3.0,21.0,6.0,13.0,Mitsubishi
11643,2022,0.35,32000,Hybrid,Automatic,Punjab,Maroon,Imported,660.0,NaN,0.0,0.0,0.0,0.0,Mitsubishi
11686,2007,0.16,85000,Petrol,Automatic,Karachi,Blue,Imported,660.0,NaN,0.0,0.0,0.0,0.0,Nissan
11763,2013,0.72,59000,Petrol,Automatic,Lahore,Grey,Imported,1800.0,NaN,0.0,0.0,0.0,0.0,Audi

In [28]:
df.groupby('color')['price'].mean().sort_values(ascending=False)

color
Ivory        1.067333
Black        0.773949
Yellow       0.723750
White        0.699438
Teal         0.600000
Burgundy     0.552609
Graphite     0.522979
Beige        0.493108
Red          0.459674
Grey         0.452522
Orange       0.440000
Blue         0.427136
Brown        0.414848
Maroon       0.411746
Silver       0.407013
Bronze       0.375849
Purple       0.360000
Titanium     0.341277
Gold         0.325755
Other        0.320000
Champagne    0.300000
Green        0.290569
Pink         0.247273
Charcoal     0.167778
Name: price, dtype: float64

In [35]:
 df['color'] = df['color'].apply(lambda x:'other' if x not in ['White','Black','Silver','Grey','Blue'] else x)

In [36]:
df['color'].value_counts()

color
White     4717
Black     2808
Silver    1754
other     1646
Grey       559
Blue       433
Name: count, dtype: int64

In [47]:
df['city'] = df['city'].apply(lambda x:'other' if x not in ['Islamabad','Punjab','Lahore','Karachi','Sindh','Un-Registered'] else x)

In [49]:
mapping = {'Lahore':'Punjab','Karachi':'Sindh'}
df['city'] = df['city'].replace(mapping)

In [51]:
(df.isnull().sum() / df.shape[0] )* 100

year               0.000000
price              0.000000
Km_travelled       0.000000
fuel_type          0.000000
transmission       0.000000
city               0.000000
color              0.000000
assembly           0.000000
engine             0.000000
body_type          1.359403
interior_scores    0.000000
exterior_scores    0.000000
safety_scores      0.000000
comfort_scores     0.000000
company            0.000000
dtype: float64

In [52]:
df.head(1)

,year,price,Km_travelled,fuel_type,transmission,city,color,assembly,engine,body_type,interior_scores,exterior_scores,safety_scores,comfort_scores,company
0,2020,0.64,50000,Petrol,Automatic,Sindh,White,Imported,2000.0,Crossover,34.0,30.0,38.0,42.0,KIA

In [60]:
df['body_type'].fillna(df['body_type'].mode()[0], inplace=True)

In [61]:
(df.isnull().sum() / df.shape[0] )* 100

year               0.0
price              0.0
Km_travelled       0.0
fuel_type          0.0
transmission       0.0
city               0.0
color              0.0
assembly           0.0
engine             0.0
body_type          0.0
interior_scores    0.0
exterior_scores    0.0
safety_scores      0.0
comfort_scores     0.0
company            0.0
dtype: float64